steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/run-nginx', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/run-nginx']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'run-nginx', '--image', 'gcr.io/$PROJECT_ID/run-nginx', '--region', 'asia-northeast1','--platform', 'managed', '--quiet', '--allow-unauthenticated']
images:
- gcr.io/$PROJECT_ID/run-nginx
